name: ci-build

on:
  pull_request:
    branches:
      - master

jobs:
  # lint is handled by pre-commit ci conf
  logo-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: debug DELETE ME
        run: |
          echo ${{ github.event.pull_request.base}}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install pytest-cov
        run: pip install pytest-cov
      - name: Install icclim
        run: python -m pip install -e .
      - name: Generate logos
        run: |
          python ./tools/update_logo_version.py ./doc/source/_static/logo_icclim_colored__base.svg ./doc/source/_static/logo_icclim_colored__displayed.svg
          python ./tools/update_logo_version.py ./doc/source/_static/logo_icclim_grey__base.svg ./doc/source/_static/logo_icclim_grey__displayed.svg
          python ./tools/update_logo_version.py ./doc/source/_static/logo_icclim_white__base.svg ./doc/source/_static/logo_icclim_white__displayed.svg
      - name: create local ref
        run: |
          git fetch ${{ github.event.pull_request.base.clone_url }} ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.head_ref }}
      - name: setup git config
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot - logo updater"
          git config user.email "<>"
      - name: commit
        run: |
          # Stage the file, commit and push
          git add doc/source/_static/*__displayed.svg
          # Ignore error cases with `|| true`
          git commit -m "MAINT: Update logos" || true
          git push ${{ github.event.pull_request.base.clone_url }} ${{ github.event.pull_request.base.ref }}
